CREATE TABLE IF NOT EXISTS requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    event_id BIGINT NOT NULL,
    requester_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL
);

-- Indexes for better query performance
DROP INDEX IF EXISTS idx_requests_event;
DROP INDEX IF EXISTS idx_requests_event_requester;

CREATE INDEX idx_requests_event ON requests(event_id);
CREATE INDEX idx_requests_event_requester ON requests(event_id, requester_id);